// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LoginincorectoTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void loginincorecto() {
    driver.Navigate().GoToUrl("https://localhost:44390/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
    driver.FindElement(By.LinkText("Acerca de")).Click();
    Assert.That(driver.FindElement(By.CssSelector("h2")).Text, Is.EqualTo("About."));
    driver.FindElement(By.LinkText("Contacto")).Click();
    Assert.That(driver.FindElement(By.CssSelector("h2")).Text, Is.EqualTo("Contact."));
    driver.FindElement(By.Id("loginLink")).Click();
    driver.FindElement(By.CssSelector("h2")).Click();
    Assert.That(driver.FindElement(By.CssSelector("h2")).Text, Is.EqualTo("Iniciar sesión."));
    driver.FindElement(By.Id("Email")).Click();
    driver.FindElement(By.Id("Email")).SendKeys("kk");
    driver.FindElement(By.CssSelector(".form-group:nth-child(4) > .col-md-10")).Click();
    Assert.That(driver.FindElement(By.Id("Email-error")).Text, Is.EqualTo("El campo Correo electrónico no es una dirección de correo electrónico válida."));
    driver.FindElement(By.Id("Email")).Click();
    driver.FindElement(By.Id("Email")).SendKeys("kk@kk");
    driver.FindElement(By.Id("Password")).SendKeys("dddd");
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.CssSelector(".form-horizontal")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".validation-summary-errors li")).Text, Is.EqualTo("Intento de inicio de sesión no válido."));
  }
}
